spring.application.name=projeto-individual-back

spring.datasource.url=jdbc:mysql://localhost:3306/lista_filmes
spring.datasource.username=root
spring.datasource.password=Analista27@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver